"""Exportable report: automated findings and clinician conclusions are kept in separate, labelled sections."""

from __future__ import annotations

import html
import uuid
from datetime import datetime, timezone

from .models import Recording, User
from .serializers import MODEL_STATUS_TEXT, RESULT_TIER_TEXT


def build_report(r: Recording, user: User) -> dict:
    a = r.analyses[-1] if r.analyses else None
    q = a.quality_report if a else None
    model_section: dict = {"status": a.model_status if a else "not_analyzed",
                           "status_text": MODEL_STATUS_TEXT.get(a.model_status, "") if a else "Recording has not been analysed."}
    if a:
        model_section["result_tier"] = a.result_tier
        model_section["result_tier_text"] = RESULT_TIER_TEXT[a.result_tier]
        if a.model_status == "completed" and a.model_output:
            mo = a.model_output
            model_section.update({
                "model": {"name": a.model_name, "version": a.model_version,
                          "validation_status": (mo.get("model_card") or {}).get("validation_status"),
                          "intended_use": (mo.get("model_card") or {}).get("intended_use")},
                "abstained": mo.get("abstained"),
                "abstain_reason": mo.get("abstain_reason"),
                "scores": mo.get("scores", []),
                "limitations": mo.get("limitations", []),
                "tier_reason": mo.get("tier_reason"),
            })
        if a.error:
            model_section["error"] = a.error
    return {
        "report_id": str(uuid.uuid4()),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": user.full_name,
        "is_demo": r.is_demo,
        "patient": {"pseudonym": r.patient.pseudonym, "synthetic": r.patient.is_synthetic},
        "recording": {"id": r.id, "recorded_at": (r.recorded_at or r.created_at).isoformat(), "device_type": r.device_type,
                      "auscultation_site": r.auscultation_site, "environment": r.environment, "duration_s": r.duration_s,
                      "sample_rate": r.sample_rate, "sha256": r.sha256},
        "automated": {
            "analysis_timestamp": a.created_at.isoformat() if a else None,
            "pipeline_version": a.pipeline_version if a else None,
            "quality": {"overall": q["overall"], "headline": q["headline"],
                        "checks": [{k: c[k] for k in ("label", "status", "value", "threshold", "explanation")} for c in q["checks"]]} if q else None,
            "model": model_section,
        },
        "clinician": {
            "review_status": r.review_status,
            "reviews": [{"at": v.created_at.isoformat(), "by": v.reviewer.full_name if v.reviewer else None, "status": v.status,
                         "note": v.note, "conclusion": v.clinician_conclusion, "flagged_for_followup": v.flagged_for_followup}
                        for v in r.reviews],
        },
        "statements": [
            "Automated outputs are decision support and are not a diagnosis.",
            "A negative or low model score does not establish that the heart is healthy.",
            "Clinician conclusions are entered by the named reviewer and are not generated by software.",
            "Smartphone and other non-medical microphones are not equivalent to a medical-grade electronic stethoscope.",
        ] + (["DEMO / SYNTHETIC DATA — not a real patient."] if r.is_demo else []),
    }


def _e(v) -> str:
    return html.escape("" if v is None else str(v))


def render_report_html(rep: dict) -> str:
    auto, m, clin = rep["automated"], rep["automated"]["model"], rep["clinician"]
    q = auto["quality"]
    checks = "".join(f"<tr><td>{_e(c['label'])}</td><td class='s-{_e(c['status'])}'>{_e(c['status'])}</td><td>{_e(c['value'])}</td><td>{_e(c['explanation'])}</td></tr>"
                     for c in (q["checks"] if q else []))
    scores = "".join(f"<li>{_e(s['label'])}: {_e(s['score'])} <em>({_e(s['score_type'].replace('_', ' '))})</em></li>" for s in m.get("scores", []))
    lims = "".join(f"<li>{_e(x)}</li>" for x in m.get("limitations", []))
    reviews = "".join(f"<div class='rev'><b>{_e(v['by'])}</b> · {_e(v['at'][:16].replace('T', ' '))} · {_e(v['status'])}"
                      f"{' · FLAGGED for further evaluation' if v['flagged_for_followup'] else ''}"
                      f"<p>{_e(v['note'])}</p>{'<p><b>Conclusion:</b> ' + _e(v['conclusion']) + '</p>' if v['conclusion'] else ''}</div>"
                      for v in clin["reviews"]) or "<p>No clinician review recorded.</p>"
    stmts = "".join(f"<li>{_e(s)}</li>" for s in rep["statements"])
    demo = "<div class='demo'>DEMO / SYNTHETIC DATA — NOT A REAL PATIENT</div>" if rep["is_demo"] else ""
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>CardioLens report {_e(rep['patient']['pseudonym'])}</title>
<style>body{{font:14px/1.5 system-ui,sans-serif;color:#0f1d33;max-width:860px;margin:24px auto;padding:0 16px}}
h1{{font-size:20px}}h2{{font-size:16px;border-bottom:1px solid #cbd5e1;padding-bottom:4px;margin-top:28px}}
table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #e2e8f0;padding:4px 6px;text-align:left;vertical-align:top}}
.s-fail{{color:#9a3412;font-weight:600}}.s-warn{{color:#a16207}}.s-pass{{color:#0f766e}}
.tag{{display:inline-block;padding:2px 8px;border-radius:4px;background:#e2e8f0}}.demo{{background:#fef3c7;padding:8px;font-weight:700;text-align:center}}
.rev{{border-left:3px solid #0f766e;padding-left:8px;margin:8px 0}}small{{color:#475569}}</style></head><body>
{demo}<h1>CardioLens AI — Recording report</h1>
<small>Report {_e(rep['report_id'])} · generated {_e(rep['generated_at'][:19].replace('T', ' '))} UTC by {_e(rep['generated_by'])}</small>
<p>Patient <b>{_e(rep['patient']['pseudonym'])}</b> · Recording #{_e(rep['recording']['id'])} · {_e(rep['recording']['recorded_at'][:16].replace('T', ' '))}
· {_e(rep['recording']['device_type'])} · site: {_e(rep['recording']['auscultation_site'])} · {_e(rep['recording']['duration_s'])} s @ {_e(rep['recording']['sample_rate'])} Hz</p>
<h2>Section A — Automated signal-quality analysis</h2>
<p><span class="tag">{_e(q['overall'] if q else 'n/a')}</span> {_e(q['headline'] if q else '')}</p>
<table><tr><th>Check</th><th>Status</th><th>Value</th><th>Explanation</th></tr>{checks}</table>
<small>Pipeline {_e(auto['pipeline_version'])} · analysed {_e((auto['analysis_timestamp'] or '')[:19].replace('T', ' '))} UTC</small>
<h2>Section B — Automated model output</h2>
<p><span class="tag">{_e(m.get('result_tier_text', ''))}</span></p><p>{_e(m.get('status_text'))}</p>
{'<p>Model: ' + _e(m['model']['name']) + ' v' + _e(m['model']['version']) + ' (' + _e(m['model']['validation_status']) + ')</p>' if m.get('model') else ''}
{'<p>Model abstained: ' + _e(m.get('abstain_reason')) + '</p>' if m.get('abstained') else ''}
{'<ul>' + scores + '</ul>' if scores else ''}{'<p><b>Limitations</b></p><ul>' + lims + '</ul>' if lims else ''}
{'<p>' + _e(m['error']) + '</p>' if m.get('error') else ''}
<h2>Section C — Clinician review (entered by clinicians)</h2><p>Status: <b>{_e(clin['review_status'])}</b></p>{reviews}
<h2>Important statements</h2><ul>{stmts}</ul></body></html>"""
